#!/bin/bash
# Example cmd for step5, remember to change all paths in example files and flags

ROSETTA="/home/liyunhao/Rosetta/main/source/bin"

# 5.1_5.2 ColabFold
cd 5.1_5.2_ColabFold
colabfold_batch --templates \
    --amber --use-gpu-relax --num-recycle 6 \
    dMKR_dif_cubic_3759_traj2_T0.2_0_2_model_4.0_r8_af2_000000001_0001_0001_0032_T0.2_0_4_proteinmpnn.fasta \
    output/dMKR_dif_cubic_3759_traj2_T0.2_0_2_model_4.0_r8_af2_000000001_0001_0001_0032_T0.2_0_4_proteinmpnn_output

# 5.3 Final_relax
cd ../5.3_final_relax
"$ROSETTA"/rosetta_scripts.mpi.linuxgccrelease \
    @final_relax.flags \
    -s dMKR_dif_cubic_3759_traj2_T0.2_0_2_model_4.0_r8_af2_000000001_0001_0001_0032_T0.2_0_4_proteinmpnn.pdb \
    -parser:script_vars lig_res=131 cat_res=42,44,54,61,84,85 cst_file=dMKR_dif_cubic_3759_traj2_T0.2_0_2_model_4.0_r8_af2_000000001_0001_0001_0032_T0.2_0_4_proteinmpnn.cst
